/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stroom.dataGenerator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        EventGen classUnderTest = new EventGen();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
