/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stroom.dataGenerator;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import stroom.dataGenerator.config.EventGenConfig;
import stroom.dataGenerator.config.EventStreamConfig;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Random;

public class EventGen {

    private final EventGenConfig config;

    public EventGen(String pathToConfig) throws IOException {
        ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
        mapper.findAndRegisterModules();
        config = mapper.readValue(new File(pathToConfig), EventGenConfig.class);
    }

    public void go () throws FileNotFoundException {
        Random random = new Random(config.getSeed());
        for (EventStreamConfig streamConfig : config.getStreams()){
            EventStreamProcessor streamProcessor = new EventStreamProcessor (config, streamConfig);
            
        }

    }

    public static void main(String[] args) {
        if (args.length != 1){
            System.err.println ("Please provide path to config YAML as application parameter");
        } else {
            try {
                EventGen app = new EventGen(args[0]);
                app.go();
            } catch (Exception ex){
                System.err.println ("Fatal Error due to " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    }
}
